import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../../app/globals.css';
import DockMenu from '@/components/dock';
import { ThemeParticles } from '@/components/particlesBackground';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { cn } from '@/lib/utils';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Yuri Gonçalves',
  description: 'Generated by create next app',
};

interface Messages {
  LayoutPage?: {
    copyright?: string;
  };
}

async function loadMessages(locale: string) {
  switch (locale) {
    case 'en':
      return (await import('../../../messages/en.json')).default;
    case 'es':
      return (await import('../../../messages/es.json')).default;
    case 'pt':
      return (await import('../../../messages/pt.json')).default;
    default:
      return (await import('../../../messages/pt.json')).default;
  }
}

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { children } = props;
  const { locale } = await props.params;

  let messages: Messages;
  try {
    messages = await loadMessages(locale);
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} data-theme='light'>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          'antialiased relative min-h-screen flex flex-col'
        )}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider attribute='class' defaultTheme='light'>
            <ThemeParticles />

            <main className='flex-grow relative z-10'>
              {children}
              <div className='absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-background to-transparent' />
            </main>

            <footer className='z-10 text-sm text-muted-foreground py-6 px-10'>
              {messages?.LayoutPage?.copyright?.replace(
                '{year}',
                String(new Date().getFullYear())
              )}
            </footer>

            <div className='fixed bottom-5 left-0 right-0 z-50 p-2'>
              <DockMenu />
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
